apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mywebdeploy
  name: mywebdeploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mywebdeploy
  template:
    metadata:
      labels:
        app: mywebdeploy
    spec:
      containers:
      - image: nginx
        name: nginx
